const ResearchMethodologies = [
  {
    desc: "This lesson describes what is research, why to do research, difference between qualititative and quantitative research. Besides that, it also focuses on importance of documenting research work and various venues of propagating your research work.",
    recordId: "",
    title: "Introduction of Research & Research Paper",
    type: "video",
    videoID: "9ycXyHCCE6j",
  },
  {
    desc: "The importance of reading in a research work is explained via this lession. The researcher must have up-to-date knowledge of state of the art and open problems in his/her research area. How to start reading with a broader perspective and then how to narrow down area of interest is also explained. The most important aspect of research which is often neglected by new researchers is plagiarism. The importance of plagiarism and the tools to detect plagiarism and how to present your research in an ethical manner is also explained.",
    recordId: "",
    title: "Importance of Reading & Plagiarism",
    type: "video",
    videoID: "BEFX3aB3sxZ",
  },
  {
    desc: "This lesson focuses on various parts of research paper inlcuding, title, abstarct, keywords, introduction, literature review, assumptions, methodology, proofs, results, conclusion and references etc. Do's and Dont's are discussed for various aspect of a research paper. By applying these do's and dont's one will be able to improve quality of research paper and its reach.",
    recordId: "",
    title: "Anatomy of Research Paper",
    type: "video",
    videoID: "5JAUzRTn3sa",
  },
  {
    desc: "Intellectual property right is another aspect of research which has gained importance in recent years. In this lesson, alss aspects related to IPR and patent have been covered which will help you to secure your researhc from being misused without your knowledge. Secondly, the startup eco system, various difficulties in opening a startup and how to overcome these has also been explained.",
    recordId: "",
    title: "IPR Patent Startup",
    type: "video",
    videoID: "6dXP8ygRKNA",
  },
  {
    desc: "Various government and non government agencies call for research proposal every now and then in order to solve the problem of industry and society. Writing a good research proposal is both art and science. In this lession, tips and tricks to write good research proposal has been explained ",
    recordId: "",
    title: "How to write project proposal",
    type: "video",
    videoID: "72ajtt37U7y",
  },
  {
    desc: "In this video you'll learn about Patent, New Means , Inventive Step, Industrial Application ,What Cannot be a Patented ,Patent Application Filing & it's process",
    recordId: "",
    title: "Patent & it's Application",
    type: "video",
    videoID: "A6bFyEA6tmb",
  },
  {
    desc: "In this animated video you'll learn the difference between search & research",
    recordId: "",
    title: "Search & Research",
    type: "video",
    videoID: "76PQKN2r4AG",
  },
  {
    desc: "Discover the transformative power of research in this insightful video. From the people who benefit from its outcomes to the innovative strides made by faculty members and entrepreneurs, explore how research shapes our world for the better. Join us as we uncover the tangible benefits and real-world impact of research across different sectors.",
    recordId: "",
    title: "Research: Impact and Innovation",
    type: "video",
    videoID: "4ASTaDjggCH",
  },
  {
    desc: " Explore the fundamental types of research, from quantitative and qualitative approaches to the distinctions between pure and applied research. Delve into the nuances of exploratory and descriptive research, and uncover the significance of diagnostic studies and evaluation research in understanding complex phenomena. Learn about experimental designs and the power of surveys in gathering valuable insights. Whether you're a student, researcher, or enthusiast, this video offers a comprehensive overview of research methodologies to deepen your understanding of the research process.",
    recordId: "",
    title: "Understanding Research: Types and Methodologies",
    type: "video",
    videoID: "p3htgpF8JC8",
  },
  {
    desc: "Discover the core skills essential for successful research: mathematics, writing, analytical thinking, and computer proficiency. Stay abreast of the latest trends in your subject area and explore related fields to broaden your expertise. Whether you're a beginner or seasoned researcher, this video is your roadmap to excellence.",
    recordId: "",
    title: "Essential Skills for Research Success",
    type: "video",
    videoID: "5UDXYaQfSyk",
  },
  {
    desc: "Explore the tangible results of research, from papers and patents to white papers, project reports, books, and theses. Discover how each outcome contributes to knowledge dissemination and innovation.",
    recordId: "",
    title: "Research Outcomes",
    type: "video",
    videoID: "5e8J7cKcdQ7",
  },
  {
    desc: "Embark on your research journey by selecting a domain that aligns with your educational background, interests, and societal relevance. Dive deeper by choosing a sub-domain and building fundamental knowledge. Assess the existence of a research community and available materials to support your exploration.",
    recordId: "",
    title: "Navigating Your Research Domain",
    type: "video",
    videoID: "5sbeSgfurGS",
  },
  {
    desc: "Explore the process of selecting a research topic by considering factors like personal interests, societal relevance, and community engagement. Learn how to assess the availability of reading materials and experiment setups to support your research endeavors.",
    recordId: "",
    title: "Choosing Your Research Topic",
    type: "video",
    videoID: "B6QzG46attx",
  },
  {
    desc: "Understand the crucial role of fundamentals in research and how they form the bedrock of your work. Explore essential resources such as books, the internet, research papers, and peer collaboration to enrich your research journey. Learn the significance of well-crafted project proposals and reports in communicating your findings effectively.",
    recordId: "",
    title: "Building Strong Foundations for Research",
    type: "video",
    videoID: "8hetZmpEFsS",
  },
  {
    desc: "Discover the vital importance of current literature in shaping and informing your research endeavors. Explore diverse sources of literature, including academic journals, books, online databases, and scholarly publications. Learn practical strategies for getting started with your research journey, leveraging the wealth of available literature to inform and inspire your work.",
    recordId: "",
    title: "Harnessing the Power of Current Literature in Research",
    type: "video",
    videoID: "82ZxD28GSun",
  },

  {
    desc: "Learn the significance of identifying research gaps and uncover practical strategies for locating them within your field. Explore the different types of gaps that exist and understand how they inform the direction of your research. Discover effective methods for filling these gaps and contributing valuable insights to the academic discourse.",
    recordId: "",
    title: "Navigating Research Gaps: Identification and Solutions",
    type: "video",
    videoID: "ARx6u3PFFBh",
  },
  {
    desc: "Delve into the various types of research setups, including experimental setups and simulators for hands-on investigation. Explore the use of surveys and questionnaires as valuable tools for data collection and analysis. Gain insights into how these setups are utilized across different research methodologies to address diverse research questions.",
    recordId: "",
    title: "Exploring Research Setups",
    type: "video",
    videoID: "7KYsRs6ZnKX",
  },
  {
    desc: "Delve into the world of experimental research and discover the strategies for conducting successful experiments. Explore the importance of experimental setups, performance parameters, and suitable assumptions in achieving reliable results. Learn how to optimize your experiments by considering factors like scale and multiple runs, ensuring the validity and reproducibility of your findings.",
    recordId: "",
    title: "Conducting Experiments",
    type: "video",
    videoID: "6XxB4NyjTcP",
  },

  {
    desc: "Discover diverse methods for presenting your research findings, including textual descriptions, charts, graphs, and visual aids. Learn how to effectively communicate your results through these mediums to engage your audience and convey complex information clearly and concisely.",
    recordId: "",
    title: "Effective Presentation Methods for Research Findings",
    type: "video",
    videoID: "5nSpdZxXAGq",
  },
  {
    desc: "Learn the essential criteria for creating impactful research titles and explore helpful do's and don'ts to guide your title selection process. Discover different types of titles and understand how to choose the most suitable one for your research project.",
    recordId: "",
    title: "Crafting Compelling Research Titles: Criteria, Do's & Don'ts",
    type: "video",
    videoID: "9SAb59abqYR",
  },
  {
    desc: "Unlock the art of abstract writing by understanding its key components and learning expert tips to craft compelling summaries of your research. Explore common mistakes to avoid, ensuring your abstract effectively captures the essence of your work and engages your audience.",
    recordId: "",
    title: "Mastering Abstract Writing",
    type: "video",
    videoID: "795Smed3S6F",
  },

  {
    desc: "Explore the definition and critical importance of keywords in research. Learn effective strategies for selecting and utilizing keywords to enhance the discoverability and impact of your work. Discover common errors to avoid, ensuring your research reaches its intended audience with precision and clarity.",
    recordId: "",
    title: "Keyword Mastery: Maximizing Research Visibility",
    type: "video",
    videoID: "4UKAPm9mRue",
  },
  {
    desc: " Explore the purpose, essential components, and common mistakes in writing the introduction of a research paper. Gain insights into how to captivate your audience, establish the relevance of your study, and set the stage for your research findings.",
    recordId: "",
    title: "Crafting an Effective Research Paper Introduction",
    type: "video",
    videoID: "3mRRN7gsHh2",
  },
  {
    desc: "Understand the purpose, key elements, and effective writing strategies for the Related Work section in your research paper. Learn how to critically review existing literature, identify gaps, and position your work within the broader academic discourse.",
    recordId: "",
    title: "Constructing a Comprehensive Related Work Section",
    type: "video",
    videoID: "9tnBnP7qnYz",
  },
  {
    desc: "Explore the importance and definitions of System Model & Assumptions (SMA) in research. Learn how SMA provides a structured framework for analyzing complex systems and guiding research methodologies effectively.",
    recordId: "",
    title: "System Model and Assumptions",
    type: "video",
    videoID: "3f95XmUZajd",
  },

  {
    desc: "Dive into the process of developing a proposed solution by identifying problems, conducting cost-benefit analysis, anticipating outcomes, evaluating alternatives, and addressing limitations and challenges. Gain insights into effective presentation techniques to communicate your proposed solution convincingly.",
    recordId: "",
    title: "Developing a Proposed Solution",
    type: "video",
    videoID: "789NAZnhbAE",
  },
  {
    desc: "Delve into the definition and role of Mathematical Analysis (MA) in research, uncover its wide-ranging applications across various fields, and understand the methodology behind its implementation. Discover the benefits of utilizing MA techniques in problem-solving, decision-making, and enhancing understanding of complex systems.",
    recordId: "",
    title: "Exploring Mathematical Analysis",
    type: "video",
    videoID: "Af6GZbk6GMN",
  },
  {
    desc: "Learn about the key elements involved in presenting research results effectively, including structuring your findings, utilizing tables, graphs, and charts, interpreting experimental setups and results, and addressing limitations. Gain practical insights into how to create compelling presentations that communicate your results clearly and persuasively.",
    recordId: "",
    title: "Crafting Effective Result Presentations",
    type: "video",
    videoID: "3eKenp5JT8j",
  },
  {
    desc: "Explore the purpose of the research conclusion and learn how to effectively summarize your findings. Understand the implications and significance of your research, address limitations, propose future directions, and offer final thoughts to provide closure to your study.",
    recordId: "",
    title: "Concluding Your Research",
    type: "video",
    videoID: "55tufRBU7Yj",
  },

  {
    desc: "Understand the purpose of references and explore various citation styles and reference list formats. Learn about tools and resources for managing references, as well as best practices for avoiding plagiarism and maintaining academic integrity. Identify common mistakes and how to avoid them when creating your reference list.",
    recordId: "",
    title: "References: Purpose, Styles, and Integrity",
    type: "video",
    videoID: "3TC4NC88mMd",
  },
  {
    desc: "Explore the dos and don'ts of paper formatting to ensure your work meets professional standards. Identify common mistakes to avoid in formatting your paper, promoting readability and adherence to journal guidelines.",
    recordId: "",
    title: "Navigating Paper Formatting",
    type: "video",
    videoID: "Eth5kuF55Yg",
  },
  {
    desc: "Explore the major formatting styles used in academic writing, including APA, MLA, and Chicago styles. Understand how to effectively utilize each style depending on the requirements of your discipline and publication. Learn about the major elements of formatting, such as title pages, headings, citations, and references, to ensure consistency and clarity in your writing.",
    recordId: "",
    title: "Formatting Styles: Understanding, Utilization, and Elements",
    type: "video",
    videoID: "4aUT5JFutMu",
  },

  {
    desc: "Delve into the world of editing tools with a comparison of LaTeX and WYSIWYG editors. Learn about the advantages of LaTeX in terms of precise formatting and compatibility with scientific documents. Discover the benefits of WYSIWYG editors for their user-friendly interface and real-time visual feedback.",
    recordId: "",
    title: "Editing Tools Unveiled",
    type: "video",
    videoID: "BuSSbKe4Bz4",
  },
  {
    desc: "Explore various publishing venues for disseminating your research, including academic journals, conferences, edited books, patents, theses, research reports, and white papers. Learn about the unique characteristics and considerations for each venue to make informed decisions about where to publish your work for maximum impact and visibility.",
    recordId: "",
    title: "Choosing the Right Publishing Venue",
    type: "video",
    videoID: "BkyRpFKtdAB",
  },
  {
    desc: "Discover the essential factors to consider when selecting a conference for presenting your research. Learn about considerations such as the conference's reputation, relevance to your field, location, audience, submission deadlines, and publication opportunities. Gain insights into how to prioritize these factors to ensure your participation in a conference that aligns with your research goals and maximizes networking and dissemination opportunities.",
    recordId: "",
    title: "Selecting the Perfect Conference",
    type: "video",
    videoID: "77gX4y9KM9r",
  },
  {
    desc: "Explore the step-by-step process of conference publication, including instructions for authors, manuscript preparation, adherence to major referencing styles, manuscript submission, and presentation guidelines. Gain insights into each stage of the publication process to ensure a smooth and successful conference experience.",
    recordId: "",
    title: "Conference Publication: Essential Steps",
    type: "video",
    videoID: "8C4CdQczfS8",
  },
  {
    desc: "Discover the importance of proofreading in ensuring accuracy and professionalism in your writing. Learn essential steps to follow when proofreading your work, including checking for grammar and punctuation errors, clarity and coherence of ideas, formatting consistency, and overall readability. Master the art of proofreading to enhance the quality and impact of your documents.",
    recordId: "",
    title: "Proofreading: Importance and Steps",
    type: "video",
    videoID: "5kQEKmetMgA",
  },
  {
    desc: "Learn systematic approaches for reviewing research papers effectively. From skimming through the document to analyzing key sections like the title, abstract, introduction, methodology, results, discussion, conclusion, and references, discover how to identify and address mistakes comprehensively. Master the art of critical reading to enhance the quality and clarity of research manuscripts.",
    recordId: "",
    title: "Effective Review Techniques",
    type: "video",
    videoID: "B6nMZGZAEfj",
  },
  {
    desc: "Explore a variety of grammar tools designed to assist writers in identifying and correcting grammatical errors. From Grammarly and Hemingway Editor to ProWritingAid and Language Tool, discover how these tools can enhance the clarity, coherence, and professionalism of your writing.",
    recordId: "",
    title: "Harnessing Grammar Tools",
    type: "video",
    videoID: "3Rr3bAppUsC",
  },

  {
    desc: "Learn how to effectively revise your manuscript after receiving reviewer comments. Identify common themes in the feedback, create a comprehensive revision plan, and implement changes strategically to address the reviewers' concerns. Discover strategies for seeking clarification when needed to ensure your revised manuscript meets the journal's standards and expectations.",
    recordId: "",
    title: "Navigating Revision After Reviewer Comments",
    type: "video",
    videoID: "9yrq47gSHeq",
  },
];

const ResearchMethodologiesSeq = [
  "t8URrJCC8k99uuwAwi6e",
  "U9gb1x1RVIqvsPnAqsMm",
  "MvKSiB7khGy8cNlPsFQB",
  "ixAl8sQSLTQFmLjHUZRN",
  "2SS15uMbQjQf3syJq6us",
  "77Gqimb6Icm9BtXDIyUM",
  "bpoJMjEE1TtkG9dMUw7w",
  "3aqM5G6dPG8YmTnF7bpI",
  "XKG4byQrVuMtY31fAmCd",
  "kxqFQmHAkUlRYOzMGDCU",
  "vV2ZQRbeBapCHsfypDHv",
  "hfjD2O1wW870jfuO0Mq4",
  "RdwjlzEvXG0ch20aaxdg",
  "1W7QGuSLr29meZDNKAbC",
  "goh35UdpXrRtof4hFdOD",
  "9mYLPU8FMXMz8b5UpW3m",
  "Dj0m9cPeQvVqOAwQ7zcM",
  "vY26WbAiu12CpCqfIAGd",
  "0G84Is9Dyo60FZeawusf",
  "OAdFYmlkIafAnD7IPefy",
  "JLHi1E85yd7NkNBnd2oC",
  "vxlupKCxlNknbA4BO5Wk",
  "XqrLsNWanzxq092AqsGU",
  "23A267RXQAtz1RamrzTl",
  "SPGcq08ECHXoPFML4sjY",
  "w65MxarbNEeSSrKYMtCb",
  "fZY8KyxFwe17rW8r8eyV",
  "QFtVkLf5QQB0aklfdvtw",
  "8vzjcpA8gIKO79ARyaUs",
  "uxnMsiVEFdaXMeLPgevr",
  "RZlfyO9o1egQL9gjWo1p",
  "Rb4iR6sFalupwdpIVGd2",
  "Tslzrej4tpBN8wWl2nGV",
  "NMlLaM8m1ClFSLu6XddL",
  "Jh3dEKOtqnbw1BpBXANj",
  "2fIyeRuDKZeSpFCVIsn7",
  "GJJ8ExB6BcDYfq146nKg",
  "uMIaDQPEj2UVkfYHLqIb",
  "aEhtF6BvqDPfiMSGbQ24",
  "DdNEeHRuuHQBT76pxmFN",
];

const ResearchMethodologiesCourse = [
  {
    description: "Research Methodologies",
    durationInDays: 365,
    name: "Research Methodologies",
    pricingINR: 750,
    recordId: "",
    sequence: ResearchMethodologiesSeq,
    thumbnailUrl:
      "https://firebasestorage.googleapis.com/v0/b/uieducon-df5c7.appspot.com/o/courseThumbnails%2Fresearch_methodology.svg?alt=media&token=6d12131b-3dfc-49a7-b1aa-6067a0324189",
  },
];

module.exports = { ResearchMethodologies, ResearchMethodologiesCourse };
